export const hello = 'hello'; 
export const nodes2 = [
    {"id": "the patriarchy"}, 
    {"id": "the upper class"}, 
    {"id": "the landed gentry"}, 
    {"id": "the academy"}, 
    {"id": "the insitution"}, 
    {"id": "the medical academy"}, 
    {"id": "the scholastic academy"}, 
    {"id": "the economy"}, 
    {"id": "white supremacy"}, 
    {"id": "warfare and competition"}, 
    {"id": "tit-for-tat"}, 
    {"id": "western hegemony"}, 
    {"id": "environmental exploitation"}, 
    {"id": "development/industrialization"}, 
    {"id": "resource extraction"}, 
    {"id": "resource depletion"}, 
    {"id": "exploitation/inequality"}, 
    {"id": "violence"}, 
    {"id": "divisions between people"}, 
    {"id": "othering"}, 
    {"id": "nationalism"}, 
    {"id": "geographic differences"}, 
    {"id": "differential access to resources"}, 
    {"id": "race"}, 
    {"id": "gender"}, 
    {"id": "class"}, 
    {"id": "monotheistic religion"}, 
    {"id": "one male father god"}, 
    {"id": "deifies masculinity, singular rulership (authoritarianism), heteronormative heirarchical family structure (father in rule of children and wife)"}, 
    {"id": "ownership, divisions, property, class"}, 
    {"id": "control of women's sexuality, focus on purity"}, 
    {"id": "developed in and utilized by governments with similar (dominant over subservient) ethoses"}, 
    {"id": "certain paternity is important for inheretance of land and resources"}, 
    {"id": "limiting female freedom of expression, speech, ownership"},
    {"id": "gives order to the universe by assigning philosophical 'right' of dominant social group to rule over another 'naturally subservient' group"}, 
    {"id": "use violence, fear, destruction to control subjects"}, 
    {"id": "disenfranchisement of women"}, 
    {"id": "relegation to the 'private' sphere and exclusion from the 'public' sphere"},
    {"id": "wage gap"}, 
    {"id": "rape culture (e.g. everything unearthed in the #meToo moment)"}, 
    {"id": "women prevented from equal education, property rights, platforms for speech, voting rights, right to work"}, 
    {"id": "explicit -- laws which forbid"},
    {"id": "implicit -- biases that exclude"}, 
    {"id": "systematic exculation from sociatal positions of power and influence"}, 
    {"id": "disproportionate house work"}, 
    {"id": "normal functioning/lingua franca of society includes inherent denigration of women"},
    {"id": "binarized gender"}, 
    {"id": "masculine male"}, 
    {"id": "feminine female"}, 
    {"id": "any deviation from these is threatening to the status quo's order"},
    {"id":"two types of humans, whose ability to express themselves, speak, love, and participate in the world is wholly constrained by their perceived sex"},
    // //
    // {"id":"what killed sylvia "},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},
    // {"id":""},


]